output: updating output logic to support multi bootstrap
If this is not put in place, terraform will error with this issue. Currently as of terraform 0.11.11, this is not fixed.

Error: Error running plan: 1 error(s) occurred:

* module.spoke-1.module.dcos-install.module.dcos-bootstrap-install.output.depends: Resource 'null_resource.bootstrap' not found for variable 'null_resource.bootstrap.0.id'